[build]
  command = "CI='' vite build"
  publish = "/dist"

[dev]
  command = "vite"
  port = 3000
  targetPort = 5173

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "https://npi-db.org/api/:id"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin: “*”}

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
