[build]
  command = "CI='' vite build"
  publish = "/dist"

[dev]
  command = "vite"
  port = 3000
  targetPort = 5173

[[redirects]]
  from = "https://npi-db.org/api/:id"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
